<?php
/**
 * Shared column and value formatting rules for the admin data export.
 */
if (!defined('APP_INIT')) die('Direct access not permitted');

function adminExportColumns(): array
{
    return [
        'portal_unique_id' => 'Portal Unique ID',
        'username' => 'Portal Username',
        'email' => 'Email',
        'phone' => 'Phone',
        'verified' => 'Email Verified',
        'firstname' => 'First Name',
        'middlename' => 'Middle Name',
        'lastname' => 'Last Name',
        'dob' => 'Date of Birth',
        'age' => 'Age',
        'personal_gender' => 'Personal Gender',
        'blood_group' => 'Blood Group',
        'religion' => 'Religion',
        'personal_category' => 'Personal Category',
        'ews' => 'EWS',
        'obc_ncl' => 'OBC-NCL',
        'pwd' => 'PWD',
        'fathersname' => "Father's Name",
        'foccupation' => "Father's Occupation",
        'fcontact' => "Father's Contact",
        'fqualifications' => "Father's Qualification",
        'mothersname' => "Mother's Name",
        'moccupation' => "Mother's Occupation",
        'mcontact' => "Mother's Contact",
        'mqualification' => "Mother's Qualification",
        'spousename' => 'Spouse Name',
        'soccupation' => 'Spouse Occupation',
        'scontact' => 'Spouse Contact',
        'squalification' => 'Spouse Qualification',
        'permanent_address' => 'Permanent Address',
        'present_address' => 'Present Address',
        'emergency_contact' => 'Emergency Contact',
        'income' => 'Annual Income',
        'hslc_pass_year' => 'HSLC Year',
        'hslc_board' => 'HSLC Board',
        'hslc_institute' => 'HSLC Institute',
        'hslc_total_marks' => 'HSLC Total Marks',
        'hslc_obtained_marks' => 'HSLC Obtained Marks',
        'hslc_percentage' => 'HSLC Percentage',
        'hslc_division' => 'HSLC Division',
        'hslc_subjects' => 'HSLC Subjects',
        'hsslc_pass_year' => 'HSSLC Year',
        'hsslc_board' => 'HSSLC Board',
        'hsslc_institute' => 'HSSLC Institute',
        'hsslc_total_marks' => 'HSSLC Total Marks',
        'hsslc_obtained_marks' => 'HSSLC Obtained Marks',
        'hsslc_percentage' => 'HSSLC Percentage',
        'hsslc_division' => 'HSSLC Division',
        'hsslc_subjects' => 'HSSLC Subjects',
        'bachelor_pass_year' => "Bachelor's Year",
        'bachelor_board' => "Bachelor's Board",
        'bachelor_institute' => "Bachelor's Institute",
        'bachelor_total_marks' => "Bachelor's Total Marks",
        'bachelor_obtained_marks' => "Bachelor's Obtained Marks",
        'bachelor_percentage' => "Bachelor's Percentage",
        'bachelor_division' => "Bachelor's Division",
        'bachelor_subjects' => "Bachelor's Subjects",
        'masters_pass_year' => "Master's Year",
        'masters_board' => "Master's Board",
        'masters_institute' => "Master's Institute",
        'masters_total_marks' => "Master's Total Marks",
        'masters_obtained_marks' => "Master's Obtained Marks",
        'masters_percentage' => "Master's Percentage",
        'masters_division' => "Master's Division",
        'masters_subjects' => "Master's Subjects",
        'gu_registered' => 'GU Registered',
        'gu_reg_no' => 'GU Registration No.',
        'gu_reg_year' => 'GU Registration Year',
        'migrated' => 'Migrated',
        'other_university' => 'Other University',
        'gubedcet_rollno' => 'GUBEDCET Roll No.',
        'gubedcet_name' => 'GUBEDCET Name',
        'gubedcet_gender' => 'GUBEDCET Gender',
        'gubedcet_category' => 'GUBEDCET Category',
        'gubedcet_booklet_series' => 'Booklet Series',
        'gubedcet_marks' => 'GUBEDCET Total Marks',
        'gubedcet_rank' => 'GUBEDCET Rank',
        'gubedcet_correct' => 'GUBEDCET Correct Marks',
        'gubedcet_wrong' => 'GUBEDCET Wrong Marks',
        'gubedcet_unattempted' => 'GUBEDCET Unattempted Marks',
        'academic_declaration' => 'Academic Declaration',
        'payment_status' => 'Payment Status',
        'payment_id' => 'Payment ID',
        'payment_order_id' => 'Payment Order ID',
        'payment_amount' => 'Amount Paid',
        'payment_date' => 'Payment Date',
        'current_step' => 'Registration Step',
        'is_submitted' => 'Application Submitted',
        'registered_at' => 'Portal Registration Date',
    ];
}

function adminExportHasSuccessfulPayment(array $row): bool
{
    return !empty($row['successful_payment_id']);
}

function adminExportRow(array $row): array
{
    $paymentStatus = adminExportHasSuccessfulPayment($row)
        ? 'SUCCESS'
        : (strtoupper((string) ($row['latest_payment_status'] ?? '')) ?: 'NOT PAID');
    $stepLabels = ['Not Started', 'Personal', 'Academic', 'Documents', 'Payment Done'];

    return [
        'portal_unique_id' => 'RTTC-' . str_pad((string) ($row['user_id'] ?? ''), 5, '0', STR_PAD_LEFT),
        'username' => $row['username'] ?? '',
        'email' => $row['email'] ?? '',
        'phone' => $row['phone'] ?? '',
        'verified' => !empty($row['is_verified']) ? 'Yes' : 'No',
        'firstname' => $row['firstname'] ?? '',
        'middlename' => $row['middlename'] ?? '',
        'lastname' => $row['lastname'] ?? '',
        'dob' => $row['dob'] ?? '',
        'age' => $row['age'] ?? '',
        'personal_gender' => $row['personal_gender'] ?? '',
        'blood_group' => $row['blood_group'] ?? '',
        'religion' => $row['religion'] ?? '',
        'personal_category' => $row['personal_category'] ?? '',
        'ews' => !empty($row['ews']) ? 'Yes' : 'No',
        'obc_ncl' => !empty($row['obc_ncl']) ? 'Yes' : 'No',
        'pwd' => !empty($row['pwd']) ? 'Yes' : 'No',
        'fathersname' => $row['fathersname'] ?? '',
        'foccupation' => $row['foccupation'] ?? '',
        'fcontact' => $row['fcontact'] ?? '',
        'fqualifications' => $row['fqualifications'] ?? '',
        'mothersname' => $row['mothersname'] ?? '',
        'moccupation' => $row['moccupation'] ?? '',
        'mcontact' => $row['mcontact'] ?? '',
        'mqualification' => $row['mqualification'] ?? '',
        'spousename' => $row['spousename'] ?? '',
        'soccupation' => $row['soccupation'] ?? '',
        'scontact' => $row['scontact'] ?? '',
        'squalification' => $row['squalification'] ?? '',
        'permanent_address' => $row['permanent_address'] ?? '',
        'present_address' => $row['present_address'] ?? '',
        'emergency_contact' => $row['emergency_contact'] ?? '',
        'income' => $row['income'] ?? '',
        'hslc_pass_year' => $row['hslc_pass_year'] ?? '',
        'hslc_board' => $row['hslc_board'] ?? '',
        'hslc_institute' => $row['hslc_institute'] ?? '',
        'hslc_total_marks' => $row['hslc_total_marks'] ?? '',
        'hslc_obtained_marks' => $row['hslc_obtained_marks'] ?? '',
        'hslc_percentage' => $row['hslc_percentage'] ?? '',
        'hslc_division' => $row['hslc_division'] ?? '',
        'hslc_subjects' => $row['hslc_subjects'] ?? '',
        'hsslc_pass_year' => $row['hsslc_pass_year'] ?? '',
        'hsslc_board' => $row['hsslc_board'] ?? '',
        'hsslc_institute' => $row['hsslc_institute'] ?? '',
        'hsslc_total_marks' => $row['hsslc_total_marks'] ?? '',
        'hsslc_obtained_marks' => $row['hsslc_obtained_marks'] ?? '',
        'hsslc_percentage' => $row['hsslc_percentage'] ?? '',
        'hsslc_division' => $row['hsslc_division'] ?? '',
        'hsslc_subjects' => $row['hsslc_subjects'] ?? '',
        'bachelor_pass_year' => $row['bachelor_pass_year'] ?? '',
        'bachelor_board' => $row['bachelor_board'] ?? '',
        'bachelor_institute' => $row['bachelor_institute'] ?? '',
        'bachelor_total_marks' => $row['bachelor_total_marks'] ?? '',
        'bachelor_obtained_marks' => $row['bachelor_obtained_marks'] ?? '',
        'bachelor_percentage' => $row['bachelor_percentage'] ?? '',
        'bachelor_division' => $row['bachelor_division'] ?? '',
        'bachelor_subjects' => $row['bachelor_subjects'] ?? '',
        'masters_pass_year' => $row['masters_pass_year'] ?? '',
        'masters_board' => $row['masters_board'] ?? '',
        'masters_institute' => $row['masters_institute'] ?? '',
        'masters_total_marks' => $row['masters_total_marks'] ?? '',
        'masters_obtained_marks' => $row['masters_obtained_marks'] ?? '',
        'masters_percentage' => $row['masters_percentage'] ?? '',
        'masters_division' => $row['masters_division'] ?? '',
        'masters_subjects' => $row['masters_subjects'] ?? '',
        'gu_registered' => $row['gu_registered'] ?? '',
        'gu_reg_no' => $row['gu_reg_no'] ?? '',
        'gu_reg_year' => $row['gu_reg_year'] ?? '',
        'migrated' => $row['migrated'] ?? '',
        'other_university' => $row['other_university'] ?? '',
        'gubedcet_rollno' => $row['gubedcet_rollno'] ?? '',
        'gubedcet_name' => $row['gubedcet_name'] ?? '',
        'gubedcet_gender' => $row['gubedcet_gender'] ?? '',
        'gubedcet_category' => $row['gubedcet_category'] ?? '',
        'gubedcet_booklet_series' => $row['gubedcet_booklet_series'] ?? '',
        'gubedcet_marks' => $row['gubedcet_marks'] ?? '',
        'gubedcet_rank' => $row['gubedcet_rank'] ?? '',
        'gubedcet_correct' => $row['gubedcet_correct'] ?? '',
        'gubedcet_wrong' => $row['gubedcet_wrong'] ?? '',
        'gubedcet_unattempted' => $row['gubedcet_unattempted'] ?? '',
        'academic_declaration' => !empty($row['academic_declaration']) ? 'Yes' : 'No',
        'payment_status' => $paymentStatus,
        'payment_id' => $row['successful_payment_id'] ?: ($row['latest_payment_id'] ?? ''),
        'payment_order_id' => $row['successful_order_id'] ?: ($row['latest_order_id'] ?? ''),
        'payment_amount' => $row['successful_payment_amount'] !== null
            ? number_format(((float) $row['successful_payment_amount']) / 100, 2, '.', '')
            : ($row['latest_payment_amount'] !== null ? number_format(((float) $row['latest_payment_amount']) / 100, 2, '.', '') : ''),
        'payment_date' => $row['successful_payment_date'] ?: ($row['latest_payment_date'] ?? ''),
        'current_step' => $stepLabels[(int) ($row['current_step'] ?? 0)] ?? 'Unknown',
        'is_submitted' => !empty($row['is_submitted']) ? 'Yes' : 'No',
        'registered_at' => $row['registered_at'] ?? '',
    ];
}

function adminExportCsvValue($value): string
{
    $value = (string) ($value ?? '');
    return preg_match('/^[=+\-@]/', $value) ? "'" . $value : $value;
}
